project:
  type: website
  output-dir: docs

website:
  title: "Chris Tennis Stringing"
  navbar:
    background: primary
    left:
      - about.qmd
      - strings.qmd
    #right:
      #- icon: github
      #  href: https://github.com/
      #- icon: twitter
      #  href: https://twitter.com
format:
  html:
    theme: lux
    css: styles.scss



